[package]
name = "machine-learning"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
cached = "0.53.1"
gnuplot = "0.0.43"
itertools = "0.13.0"
linreg = "0.2.0"
nalgebra = { version = "0.33.0", features = ["rand", "rayon"] }
rayon = "1.10.0"
